#!/usr/bin/env bash

case $1 in 
	debug)
		echo -e "[ DEBUG ] $2"
		;;
	info)
		echo -e "[ INFO  ] $2"
		;;

	warn)
		echo -e "[ WARN  ] $2"
		;;
	error)
		echo -e "[ ERROR ] $2"
		;;
	fatal)
		echo -e "[ FATAL ] $2"
		;;
	?)
		echo -e "[ ERROR ] Unkown loglevel!"
esac



